version: '3.9'

services:
  saba:
    tty: true
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - type: volume
        source: saba-db
        target: /saba
      - type: bind
        source: C:/Users/bouningen/.ssh/
        target: /root/.ssh
    command: [ "bash" ]

volumes:
  saba-db:
